/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tickettest;

import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.sql.SQLException;

/**
 *
 * @author Diva Nabila H
 */
public class Register extends javax.swing.JFrame {
    Connect con = new Connect ();
    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
    }
    
    public String autonumber(){
       String newID = "";
        try{
            
            String query = "SELECT * FROM usertable ORDER BY UserId DESC";
            ResultSet rs = con.executeQuery(query);
            
            if(rs.next()){
                String NoID = rs.getString(("UserId")).substring(1);
                String ID = "" + (Integer.parseInt(NoID) + 1);
                String Zero = "";
                
                if(ID.length() == 1) Zero = "000";
                else if(ID.length() == 2) Zero = "00";
                else if(ID.length() == 3) Zero = "0";
                else if(ID.length() == 4) Zero = "";
                
                newID = "U" + Zero + ID;
            } else{
                newID = "U0001";
            }
            rs.close();
        } catch(Exception e){
            System.out.println("autonumber error");
            e.printStackTrace();
        }
        return newID;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ErrorPassword = new javax.swing.JOptionPane();
        leftInputPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        PassLabel = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        txtUname = new javax.swing.JTextField();
        buttonRegister = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Create Account");
        jLabel2.setToolTipText("");

        PassLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        PassLabel.setText("Password");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Username");

        txtUname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUnameActionPerformed(evt);
            }
        });

        buttonRegister.setBackground(new java.awt.Color(12, 12, 171));
        buttonRegister.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonRegister.setForeground(new java.awt.Color(255, 255, 255));
        buttonRegister.setText("Register");
        buttonRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRegisterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout leftInputPanelLayout = new javax.swing.GroupLayout(leftInputPanel);
        leftInputPanel.setLayout(leftInputPanelLayout);
        leftInputPanelLayout.setHorizontalGroup(
            leftInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftInputPanelLayout.createSequentialGroup()
                .addGroup(leftInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(leftInputPanelLayout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(jLabel2))
                    .addGroup(leftInputPanelLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(leftInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PassLabel)
                            .addComponent(jLabel6)
                            .addComponent(buttonRegister)
                            .addComponent(txtUname, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        leftInputPanelLayout.setVerticalGroup(
            leftInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftInputPanelLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(PassLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(buttonRegister)
                .addContainerGap())
        );

        getContentPane().add(leftInputPanel, java.awt.BorderLayout.WEST);

        setSize(new java.awt.Dimension(447, 388));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtUnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUnameActionPerformed

    private void buttonRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRegisterActionPerformed
        // TODO add your handling code here:
        String id = autonumber();
        String username = txtUname.getText().toString().trim();
        String password = txtPass.getText().toString().trim();
      
        if(password.equals("") || username.equals("")){
            JOptionPane.showMessageDialog(null, "Username or Password cannot be empty!");
            
        }
        else if (password.length() < 8){
            
            JOptionPane.showMessageDialog(null, "Password must be at least 8 characters");
        }
        else{
            try{
                String sql = "INSERT INTO usertable(`Username`, `Password`, `UserId`)  VALUES (?, ?, ?)";
                PreparedStatement masuk = con.prepareStatement(sql);
                masuk.setString(1, username);
                masuk.setString(2, password);
                masuk.setString(3, id);
                masuk.executeUpdate();
                masuk.close();
                JOptionPane.showMessageDialog(null, "Welcome to Fantatix, " + username + "!");
            } catch(SQLException e){
                e.printStackTrace();
            } finally{
                this.dispose();
                Login a = new Login();
                a.setVisible(true);
            }
        }
    }//GEN-LAST:event_buttonRegisterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JOptionPane ErrorPassword;
    private javax.swing.JLabel PassLabel;
    private javax.swing.JButton buttonRegister;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel leftInputPanel;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUname;
    // End of variables declaration//GEN-END:variables
}
